### ISSUE TITLE
Nearly okay

### ISSUE THREAD

**Issue by wboeke** [tdwsl/aster-forth#2]
Hi, it's me again.
I'm playing with your new version and found some bugs. I don'want to urge on you, take your time.

-- 'See' crashes if the word is not found

-- This is forth code for 'value' and 'to':
variable #msg
create values  ' @  , ' !  ,
: value ( n 'name')
   create ,
   does>  values #msg @ cells + @ execute  0 #msg ! ;
: to  1 #msg ! ;

This works in other forth's, in aster nearly:
10 value vv
vv .  
The result should be 10, but it is 0. 'To' works as expected.

About that range check: if you enter: 
 2 3 !
then no problem is reported, but then:
3 @ .
the result is surprising: 2

**Comment by tdwsl** [comment]
Hey again,

First, I just want to say that I've fixed see, as well as other words that parse ahead. And about that range check - I'm not using real addresses, so 2 is actually a valid address - sorry if I wasn't clear about that. If you try -1 @, you should find that it says "invalid memory address".

I'm sorry to hear about value. I've tested on my system, and it does work, so I guess that's an incompatibility I need to iron out. What operating system are you running?

**Comment by wboeke** [comment]
That remark about 2 3 !, of course I understood that, you was clear enough.
My OS: Linux (what else?)

**Comment by tdwsl** [comment]
Wow, that's strange. I'm running LMDE, which is Debian-based, on x86_64. I've also tested it on JSLinux Fedora, which uses riscv64, and it also seems to work fine. I don't know what the problem could be, but I'll keep looking into it.

Anyway, in case you wanted to know, my implementation of VALUE is identical to CONSTANT, then TO sets the value that constant pushes to the stack. I'm not sure which part of that process is going wrong.

**Comment by wboeke** [comment]
Sorry, I forgot, but my 'value' code works perfectly now.
I have one small question. If I run:
./aster x1.f x2.f x3.f
then aster only will read file x1.f. Is this intentional?

**Comment by tdwsl** [comment]
Hi,
Yes, this was intentional. Arguments are accessible through argc @ and the arg word. However, I've changed it now so that if you don't use the arg word, it just runs the other files. It should work, but feel free to report any issues.
