### ISSUE TITLE
Problems with some words 

### ISSUE THREAD

**Issue by wboeke** [tdwsl/aster-forth#3]
Hello,
In your aster program, some words are implemented in forth, where in other forth's they are in C. Often this works, but e.g. the word +! gives wrong results in some circumstances. I reimplemented it in C (that was easy) and then it went okay.
But, attached to this message, there is a forth program that only contains words that are available in aster, and still it crashes. You can try it e.g. in pforth, it is the well-known 8queens problem, for 4 queens, with textual or ascii-art output. If you cannot read the attachment, please give an email address where I can post it. My email is: w dot boeke at upcmail dot nl.
If you don't want to do this: no problem!
Regards,
Wouter Boeke

[8queens-new.txt](https://github.com/tdwsl/aster-forth/files/12828435/8queens-new.txt)

**Comment by tdwsl** [comment]
Hi, thanks for getting in touch. And again, sorry for the late response.

I actually managed to find the problem this time: create wasn't allocating an extra cell, meaning that when does> added a jump to the end of a word, it overrode the space it was pointing too.

I got your attachment okay, and after my fix the 8queens piece of code works. +! is still the same, but feel free to send your fix and any others so I can implement them into the project. A shame about value still, but it's a work in progress.

Things seem fine on my end, so hopefully the 8queens demo will work for you too, but feel free to message me if it doesn't.

**Comment by wboeke** [comment]
The 8queens work, very good!

Sometimes I think that you tried to implement much words in aster using basic forth, also the words that most other forth implementors do in C. The problem then is that the return stack has to be used a lot, and that doesn't work in all cases. At that, in C some words are simple to implement but difficult in pure forth. Some implementors invent very special words as they need them, which for me is a kind of cheating.

Looking forward to your new modifications!

**Comment by tdwsl** [comment]
Yeah, you're probably right about implementing too much in forth - I definitely use the return stack a lot, particularly with do / loop. For some words, it'd probably make sense to create a separate array instead of just using the return stack.
Also, just thought I should let you know that there's a new bug with create. I just fixed it, but you'll have to download the latest version.
Thanks for your interest!

**Comment by wboeke** [comment]
Sorry for this extra comment, but I got the value_ word working. The solution is simple: you cannot implement +! in forth, you have to do it in C. Simply clone the function aster_f_sw(), and replace the ' = ' operator with ' += '. Then remove it in aster_boot.h.

**Comment by tdwsl** [comment]
No problem. It's done.
