### ISSUE TITLE
Sieve of Eratosthenes

### ISSUE THREAD

**Issue by wboeke** [tdwsl/aster-forth#6]
I tried a problem from Rosetta, the sieve of E. to generate prime numbers. A copy if the forth code is attached: sieve.txt
Other forth's give a list starting with 2 and ending with 47, but aster only shows a 2. I investicated the program and all words behaved as the should, but still the output is wrong. Maybe a nice problem to use your teeth on?

Also another sieve is attached: byte-sieve.txt. This one works also with aster.
 
[sieve.txt](https://github.com/tdwsl/aster-forth/files/13051815/sieve.txt)
[byte-sieve.txt](https://github.com/tdwsl/aster-forth/files/13061245/byte-sieve.txt)

**Comment by tdwsl** [comment]
Hi, sorry,
It looks like there was an issue with +loop where it ended up duplicating the value added. It should be fixed now, thanks for letting me know!
