### ISSUE TITLE
defer

### ISSUE THREAD

**Issue by wboeke** [tdwsl/aster-forth#7]
Hi,
I tried to implement 'defer' and 'is', because they are such interesting words. This code works in some forth's:

: noop ;
: defer ( 'name') create ['] noop , does>  @ execute ;
: >body ( xt - a) 2 cells + ;
: is ( xt 'name') ' >body ! ;

defer numeral
: tst1 1 . ;
: tst2 2 . ;
: one ['] tst1 is numeral ;
: two ['] tst2 is numeral ;
one numeral
two numeral cr

The result in aster is a crash (invalid address). I suspect that '>body' must be modified, but does'nt know how. Could you please look at this?

**Comment by tdwsl** [comment]
Hi,
You're right, sorry I didn't implement >body already. Like you said, everything worked but body, and I've fixed it now and added the words to aster.f.

**Comment by wboeke** [comment]
Sorry to reopen this issue, but did you test this code? The testprogram:

defer numeral
: tst1 1 . ;
: tst2 2 . ;
: one ['] tst1 is numeral ;
: two ['] tst2 is numeral ;
one numeral
two numeral cr

The result should be: 1 2
but I only get: stack underflow

**Comment by tdwsl** [comment]
Sorry, I forgot to add the compile time behaviour for is! Now it should actually work.
