### ISSUE TITLE
The new version, and a question

### ISSUE THREAD

**Issue by wboeke** [tdwsl/aster-forth#9]
I tried the new version of aster, and everything worked. I have a nice collection of test files and had no problems.
Would'nt it be a good idea to generate aster_boot.h with a small C program? A cold start then should be easier. Updates of aster.h could be done with a Makefile, so 'make' will do the work for you. The C file I am using
[makeboot.c.txt](https://github.com/tdwsl/aster-forth/files/14319648/makeboot.c.txt)
 is attached to this mail.
I have a small additional question. Why are you using always that old-style C code? And why are you implement strcasecmp() yourself?

**Comment by tdwsl** [comment]
Hey, thanks for the feedback. I agree with your point about makeboot and Makefiles, and I have switched the system over (thanks for the code). I guess I was just using makeboot.f to figure out the ANS file handling words.
Of course, I've also made some other changes, so let me know if anything breaks.
As for my coding style, I'll assume you're talking about me declaring all my variables at the start of a procedure? I guess I just prefer having all the local variables in a function listed at the top, like how you would in Pascal.
And about strcasecmp, thanks for the heads up - I didn't know about it before. I guess I should probably read about the C standard library functions some more.

**Comment by wboeke** [comment]
About that coding style: don't change if you use it because you like it. But many others writing a Forth compiler do it because of the available C compiler for a certain microcontroller, and that's no good reason.

If I try to understand some C code I do it bottem-up. What is this variable, is it local or global? If I have to go back to the start of a function, that is more difficult than declare and initialize the variable at the moment it is needed. Especially for loops with a local looping variable are much clearer.
